import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppinsMd = localFont({
  src: "./fonts/Poppins-Medium.ttf",
  variable: "--font-poppinsmd",
  weight: "400"
})

const poppinsBd = localFont({
  src: "./fonts/Poppins-Bold.ttf",
  variable: "--font-poppinsbd",
  weight: "600"
})

const poppinsL = localFont({
  src: "./fonts/Poppins-Light.ttf",
  variable: "--font-poppinsL",
  weight: "200"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppinsMd.variable} ${poppinsBd.variable} ${poppinsL.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
